language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev libeigen3-dev bamtools

script:
  - mkdir -p build 
  - cd build 
  - cmake ..
  - make
